[package]
name = "day3"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[[bench]]
name = "day3_benches"
harness = false

[dependencies]
color-eyre = "0.6.2"
indoc = "2.0.1"
itertools = "0.10.5"

[dev-dependencies]
criterion = "0.5.1"
