[package]
name = "day3"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[[bench]]
name = "day3_benches"
harness = false

[dependencies]
color-eyre = "0.6.2"
indoc = "1.0.8"
itertools = "0.10.5"

[dev-dependencies]
criterion = "0.4.0"
